name: Android CI

on:
  push:
    branches: [ "**" ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ "**" ]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/android/android-base:latest

    steps:
      # Checkout o repositório
      - name: Check out repository
        uses: actions/checkout@v4

      # Configurar o JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: gradle

      # Aceitar Licenças e Instalar Ferramentas
      - name: Accept licenses and install NDK and CMake
        env:
          ANDROID_HOME: /sdk
          PATH: /sdk/cmdline-tools/latest/bin:/sdk/platform-tools:$PATH
        run: |
          sdkmanager --licenses
          sdkmanager --install "ndk;25.1.8937393" "cmake;3.22.1"

      # Construir APK de release
      - name: Build App Release
        env:
          ANDROID_HOME: /sdk
          PATH: /sdk/cmdline-tools/latest/bin:/sdk/platform-tools:$PATH
        run: ./gradlew assembleRelease

      # Fazer upload do APK gerado
      - name: Upload release app
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/
